### ISSUE TITLE
Add Columns for KeyAgreement and Encryption

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/lds-jws2020#12]
@kdenhartog

Similar to the columns defining signature algorithms , can you provide some concrete preferences for x25519 ?

For example: https://github.com/panva/jose-chacha

`ECDH-ES+XC20PKW`

**Comment by OR13** [comment]
Related: https://github.com/w3c/did-core/issues/185#issuecomment-602704721

**Comment by OR13** [comment]
@kdenhartog @tplooker I am assigning you guys to this issue.

**Comment by OR13** [comment]
May want to start with pulling the types from https://github.com/digitalbazaar/minimal-cipher into a table so we can review compatibility with the base58btc encoded variants.

**Comment by awoie** [comment]
Please make sure that this is aligned with https://github.com/decentralized-identity/didcomm-messaging/blob/master/encryption.md

**Comment by OR13** [comment]
I came here to say the same. https://github.com/decentralized-identity/didcomm-messaging/pull/52/files/0c93942cfc50039eb5d14d8be0e714a1e702b94a#r436011960

**Comment by kdenhartog** [comment]
For this spec, are these tables autogenerated from the examples or manually provided in the text?

**Comment by OR13** [comment]
@kdenhartog the tables are hand crafted, and the implementation enforces them... (you could fork and add support for others).

You would only need to change this file: https://github.com/w3c-ccg/lds-jws2020/blob/master/src/getRecomendedAlg.js

**Comment by kdenhartog** [comment]
@OR13 is this issue still useful now that the implementation has been removed?

**Comment by OR13** [comment]
this issue is dead... see also: https://github.com/w3c-ccg/lds-jws2020/pull/84

recommend we close, reopen if you disagree.
